In [4]:
import numpy as np
from sklearn import preprocessing

In [3]:
X = np.array([[1.,-1.,2.],
              [2., 0., 0.],
              [0., 1., -1.]])

In [5]:
X_scaled=  preprocessing.scale(X)

In [6]:
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [8]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [9]:
X_scaled.std(axis = 0)

array([1., 1., 1.])

In [11]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])